#!/system/bin/sh
cd $HOME
rm tmp/*.env 2>/dev/null
export REPL_PID=$$
export CONSOLE="$(realpath /proc/$$/fd/1)"
env|grep -v ^ANDROID|grep -v ^BOOT|grep -v '=/mnt' |grep -v LS_COLORS > tmp/${PPID}.env
if echo $SHELL|grep -q bash
then
    reset
else
    cat tmp/${PPID}.env
fi
pwd
if true
then
    echo "REPL, you can use panda3D from it, type ctrl+c to gain access back after running app"
    #cat >/dev/null
    sleep 36000
else
    echo -n "Waiting parent process at tmp/pid.$$ : "
    sleep 1

    while true
    do
        [ -f  tmp/pid.$$ ] && break
        echo -n '.'
        sleep 1
    done
    echo "now redirecting my input to parent"
    stty echo isig intr ^Q quit undef susp undef
    sleep 1
    cat > tmp/${PPID}.in
fi

echo "press <enter>"
read
