
set(Python_VERSION "${PYMAJOR}.${PYMINOR}")
set(PYTHON_VERSION_STRING "${PYMAJOR}.${PYMINOR}")
set(PYTHON_EXTENSION_SUFFIX ".so")
set(PYTHON_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/include/python${PYMAJOR}.${PYMINOR}")
set(PYTHON_LIBRARY_DIRS "${CMAKE_INSTALL_PREFIX}/lib")
set(PYTHON_ARCH_INSTALL_DIR "${ASSETS}/python${Python_VERSION}")
set(PYTHON_LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib/python${Python_VERSION}")
set(PYTHON_FOUND YES)

message(">>>>>>>>>>>>>> python ${PYTHON_VERSION_STRING} <<<<<<<<<<<<<<<<<<<<<<<")
message(">>> CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} <<<")
message(">>> PYTHON_EXTENSION_SUFFIX=${PYTHON_EXTENSION_SUFFIX} <<<")
message(">>> PYTHON_ARCH_INSTALL_DIR=${PYTHON_ARCH_INSTALL_DIR} <<<")
message(">>> PYTHON_LIB_INSTALL_DIR=${PYTHON_LIB_INSTALL_DIR} <<<")




